// src/components/Hero.vue
<template>
  <div class="bg-black">
    <header class="absolute inset-x-0 top-0 z-50">
      <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div class="flex lg:flex-1">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Ryan Skinner</span>
            <nuxt-img src="/logo.svg" alt="logo" class="w-40 sm:w-46" />
          </a>
        </div>
      </nav>
    </header>

    <div class="relative isolate overflow-hidden pt-14">
      <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
        <div
          class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[25deg] bg-gradient-to-bl from-emerald-400 to-cyan-500 opacity-25 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
          style="clip-path: polygon(70% 50%, 100% 65%, 95% 30%, 85% 5%, 80% 10%, 70% 40%, 60% 60%, 50% 70%, 45% 55%, 40% 30%, 25% 80%, 0 70%, 15% 100%, 30% 75%, 75% 95%, 70% 50%)"
        />
      </div>
      <div class="mx-auto max-w-3xl py-32 sm:py-48 lg:py-56">
        <div class="text-center">
          <h1 class="text-6xl font-bold tracking-tight text-transparent bg-clip-text animated-gradient sm:text-8xl pb-2">
            Let's build a better internet together.
          </h1>
          <p class="mt-6 text-lg leading-8 text-gray-300 font-mono">
            I'm a creative software developer passionate about exceptional
            design, enhancing the developer experience, and pushing the boundaries of the modern web. I've collaborated
            with a diverse range of clients and utilized various technologies to craft beautiful, accessible, and
            high-performing web applications.
          </p>
        </div>
      </div>
      <div
        class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]"
        aria-hidden="true"
      >
        <div
          class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[335deg] bg-gradient-to-br from-emerald-400 to-cyan-500 opacity-25 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
          style="clip-path: polygon(70% 50%, 100% 65%, 95% 30%, 85% 5%, 80% 10%, 70% 40%, 60% 60%, 50% 70%, 45% 55%, 40% 30%, 25% 80%, 0 70%, 15% 100%, 30% 75%, 75% 95%, 70% 50%)"
        />
      </div>
    </div>
  </div>
</template>

<style>
.animated-gradient {
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}

.bg-clip-text {
  -webkit-background-clip: text;
  background-clip: text;
}
</style>

// src/components/marketing/Hero.tsx
import { rariUrl } from '@/lib/site'
import { linkStyle } from '@/lib/site/style'

export default function Hero() {
  return (
    <div className="relative isolate mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-24 lg:pt-44 lg:pb-56 max-w-6xl">
      <div
        className="absolute left-1/2 transform -translate-x-1/2 top-10 -z-10 blur-3xl sm:left-[calc(50%-9rem)] lg:bottom-[calc(50%-30rem)] lg:left-24 xl:left-[calc(20%-12rem)]"
        aria-hidden="true"
      >
        <div
          className="aspect-1108/632 w-full max-w-full bg-linear-to-r from-[#80caff] to-[#4f46e5] opacity-40"
          style={{
            clipPath: 'polygon(73.6% 51.7%, 91.7% 11.8%, 100% 46.4%, 97.4% 82.2%, 92.5% 84.9%, 75.7% 64%, 55.3% 47.5%, 46.5% 49.4%, 45% 62.9%, 50.3% 87.2%, 21.3% 64.1%, 0.1% 100%, 5.4% 51.1%, 21.4% 63.9%, 58.9% 0.2%, 73.6% 51.7%)',
          }}
        />
      </div>
      <div className="animate-fadeInMoveUp text-center">
        <h1 className="animated-gradient bg-clip-text pb-2 text-6xl font-black tracking-tight text-transparent sm:text-7xl lg:text-8xl">
          Let's build a better internet together.
        </h1>
        <h2 className="mt-6 max-w-5xl mx-auto font-mono text-xl leading-8 sm:text-2xl sm:leading-8 lg:text-2xl text-balance">
          I'm a creative software engineer passionate about exceptional design,
          enhancing the developer experience, and pushing the boundaries of the
          modern web. I'm currently building
          {' '}
          <a href={rariUrl} target="_blank" rel="noopener noreferrer" className={linkStyle.underline}>rari</a>
          , a React Server Components framework powered by a Rust runtime that delivers 53x higher throughput and 14.5x faster response times than Next.js.
        </h2>
      </div>
    </div>
  )
}
