// src/components/layout/Navbar.vue
<template>
  <div class="bg-gray-800 relative z-20">
    <div class="mx-auto max-w-6xl py-4">
      <nav class="flex justify-between items-center text-white p-4">
        <NuxtLink to="/" class="flex items-center gap-2">
          <NuxtImg src="/logo.svg" alt="Logo" width="160" height="32" />
        </NuxtLink>

        <div class="flex items-center gap-4">
          <NuxtLink to="/posts">
            Posts
          </NuxtLink>
          <ToggleColorMode class="flex" />
        </div>
      </nav>
    </div>
  </div>
</template>

// src/components/Navbar.tsx
import Button from '@/components/Button'
import RyanSkinner from '@/components/icons/RyanSkinner'

export default function Navbar() {
  return (
    <div className="relative z-20">
      <div className="mx-auto max-w-6xl py-4">
        <nav className="flex items-center justify-between p-4 text-white">
          <a href="/" className="flex items-center gap-2">
            <RyanSkinner className="w-40" />
          </a>

          <div className="flex items-center gap-4">
            <Button href="/posts">Posts</Button>
          </div>
        </nav>
      </div>
    </div>
  )
}
