// src/components/global/Footer.vue
<script setup lang="ts">
function useSocialLinks() {
  return [
    { name: 'GitHub', url: 'https://github.com/skiniks', iconClass: 'i-simple-icons-github' },
    { name: 'LinkedIn', url: 'https://www.linkedin.com/in/ryankskinner/', iconClass: 'i-simple-icons-linkedin' },
    { name: 'Bluesky', url: 'https://bsky.app/profile/ryanskinner.com', iconClass: 'i-simple-icons-bluesky' },
  ]
}

const socialLinks = useSocialLinks()
const currentYear = computed(() => new Date().getFullYear())
</script>

<template>
  <footer>
    <div class="mx-auto max-w-7xl px-6 py-12 md:flex md:items-center md:justify-between lg:px-8">
      <div class="flex justify-center space-x-6 md:order-2">
        <a
          v-for="link in socialLinks" :key="link.name" :href="link.url"
          class="w-6 h-6 sm:w-8 sm:h-8 hover:scale-105 transition-transform duration-300 ease-in-out"
          :class="link.iconClass" target="_blank" :aria-label="`Link to ${link.name}`"
        />
      </div>
      <div class="mt-8 md:order-1 md:mt-0">
        <p class="text-center text-xs leading-5 text-gray-500">
          &copy; {{ currentYear }} Ryan Skinner. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
</template>

// src/components/ui/Footer.tsx
import Bluesky from '@/components/icons/Bluesky'
import Github from '@/components/icons/Github'
import Rari from '@/components/icons/Rari'
import { getLatestCommitHash } from '@/lib/github'
import { blueskyUrl, contentLicense, contentLicenseUrl, githubRepoUrl, githubUrl, rariUrl, siteName } from '@/lib/site'
import { currentYear } from '@/lib/utils/date'

export default async function Footer() {
  const copyrightYear = currentYear()
  const commitHash = await getLatestCommitHash()

  const links = [
    {
      name: 'GitHub',
      url: githubUrl,
      icon: <Github className="h-6 w-6 relative z-10" />,
      gradient: 'from-[#fd7e14]/10 to-[#e8590c]/10',
    },
    {
      name: 'Bluesky',
      url: blueskyUrl,
      icon: <Bluesky className="h-6 w-6 relative z-10" />,
      gradient: 'from-blue-500/10 to-cyan-500/10',
    },
  ]

  return (
    <footer className="bg-gray-900 rounded-t-md border-t-2 border-gray-800">
      <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
          <p className="text-center text-sm leading-5 text-gray-300 sm:text-left order-2 sm:order-1">
            <a
              href={contentLicenseUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link relative hover:text-gray-100 transition-colors duration-200"
            >
              {contentLicense}
            </a>
            {' '}
            &copy; 2023-
            {copyrightYear}
            {' '}
            {siteName}
            {commitHash !== null && commitHash !== '' && (
              <>
                {' '}
                (
                <a
                  href={`${githubRepoUrl}/commit/${commitHash}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:underline hover:text-gray-200 transition-colors"
                >
                  {commitHash}
                </a>
                )
              </>
            )}
          </p>
          <a
            href={rariUrl}
            className="flex items-center justify-center gap-2 text-gray-300 hover:text-gray-100 transition-colors duration-200 group order-1 sm:order-2"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Built with rari"
          >
            <span className="text-sm">Built with</span>
            <Rari className="h-5 w-10 relative z-10 group-hover:opacity-80 transition-opacity" />
          </a>
          <div className="flex items-center justify-center sm:justify-end space-x-4 sm:space-x-6 order-3">
            {links.map(link => (
              <a
                key={link.name}
                href={link.url}
                className="p-2 text-gray-300 hover:text-gray-100 hover:bg-[#21262d] rounded-md transition-all duration-200 relative overflow-hidden group"
                target="_blank"
                rel="noopener noreferrer"
                aria-label={`Link to ${link.name}`}
              >
                <span className={`absolute inset-0 bg-linear-to-r ${link.gradient} opacity-0 group-hover:opacity-100 transition-opacity duration-300`}></span>
                {link.icon}
              </a>
            ))}
          </div>
        </div>
      </div>
    </footer>
  )
}
